server:
  port: 8083

topic:
  name: t.emprunt.order

spring:
  datasource:
    url: jdbc:h2:mem:livretdb
    username: sa
    password:


  h2:
    console:
      enabled: true
      path: /h2-console

